--liquibase formatted SQL

-- =========================================
-- 001: Create account_verification table
-- =========================================
--changeset christian:001
CREATE TABLE IF NOT EXISTS public.account_verification (
    id VARCHAR(255) NOT NULL,
    email VARCHAR(255)
);

--changeset christian:001.1
ALTER TABLE public.account_verification
    ADD CONSTRAINT account_verification_pkey PRIMARY KEY (id);


-- =========================================
-- 002: Create usuarios table
-- =========================================
--changeset christian:002
CREATE TABLE IF NOT EXISTS public.usuarios (
    id_usuario BIGINT NOT NULL,
    apellidos VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    email_confirmado BOOLEAN,
    estado VARCHAR(255),
    fecha_creacion TIMESTAMP(6),
    fecha_nacimiento TIMESTAMP(6),
    genero VARCHAR(255),
    nombre VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(255),
    token_confirmacion VARCHAR(255)
);

--changeset christian:002.1
ALTER TABLE public.usuarios
    ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY
      (SEQUENCE NAME public.usuarios_id_usuario_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--changeset christian:002.2
ALTER TABLE public.usuarios
    ADD CONSTRAINT user_pkey PRIMARY KEY (id_usuario);

--changeset christian:002.3
ALTER TABLE public.usuarios
    ADD CONSTRAINT UKoshmjvr6wht0bg9oivn75aajr UNIQUE (email);

--changeset christian:002.4
ALTER TABLE public.usuarios
    ADD CONSTRAINT user_estado_check CHECK (estado IN ('ACTIVE','INACTIVE'));

--changeset christian:002.5
ALTER TABLE public.usuarios
    ADD CONSTRAINT user_role_check CHECK (role IN ('ROLE_USER','ROLE_ADMIN'));


-- =========================================
-- 003: Create entrenamiento table
-- =========================================
--changeset christian:003
CREATE TABLE IF NOT EXISTS public.entrenamiento (
    id_entrenamiento BIGINT NOT NULL,
    distancia_km REAL,
    fecha TIMESTAMP(6),
    notas VARCHAR(255),
    ritmo_min_km REAL,
    tiempo_min REAL,
    id_usuario BIGINT NOT NULL,
    id_actividad BIGINT NOT NULL,
    distancia_metros REAL,
    tiempo_segundos REAL
);

--changeset christian:003.1
ALTER TABLE public.entrenamiento
    ALTER COLUMN id_entrenamiento ADD GENERATED BY DEFAULT AS IDENTITY
      (SEQUENCE NAME public.entrenamiento_id_entrenamiento_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--changeset christian:003.2
ALTER TABLE public.entrenamiento
    ALTER COLUMN id_actividad ADD GENERATED BY DEFAULT AS IDENTITY
      (SEQUENCE NAME public.entrenamiento_id_actividad_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--changeset christian:003.3
ALTER TABLE public.entrenamiento
    ADD CONSTRAINT entrenamiento_pkey PRIMARY KEY (id_entrenamiento);


-- =========================================
-- 004: Create lap table
-- =========================================
--changeset christian:004
CREATE TABLE IF NOT EXISTS public.lap (
    id_lap BIGINT NOT NULL,
    avg_heart_rate INTEGER,
    calories INTEGER,
    distance_meters REAL,
    intensity VARCHAR(255),
    max_heart_rate INTEGER,
    max_speed REAL,
    start_time TIMESTAMP(6),
    total_time_seconds REAL,
    trigger_method VARCHAR(255),
    id_entrenamiento BIGINT NOT NULL
);

--changeset christian:004.1
ALTER TABLE public.lap
    ALTER COLUMN id_lap ADD GENERATED BY DEFAULT AS IDENTITY
      (SEQUENCE NAME public.lap_id_lap_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--changeset christian:004.2
ALTER TABLE public.lap
    ADD CONSTRAINT lap_pkey PRIMARY KEY (id_lap);


-- =========================================
-- 005: Create lap_extension table
-- =========================================
--changeset christian:005
CREATE TABLE IF NOT EXISTS public.lap_extension (
    id_lap_extension BIGINT NOT NULL,
    avg_run_cadence INTEGER,
    avg_speed REAL,
    max_run_cadence INTEGER,
    id_lap BIGINT NOT NULL
);

--changeset christian:005.1
ALTER TABLE public.lap_extension
    ALTER COLUMN id_lap_extension ADD GENERATED BY DEFAULT AS IDENTITY
      (SEQUENCE NAME public.lap_extension_id_lap_extension_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--changeset christian:005.2
ALTER TABLE public.lap_extension
    ADD CONSTRAINT lap_extension_pkey PRIMARY KEY (id_lap_extension);

--changeset christian:005.3
ALTER TABLE public.lap_extension
    ADD CONSTRAINT UK4mfu566o0pk4w49q8ieqd9bpb UNIQUE (id_lap);


-- =========================================
-- 006: Create notificacion table
-- =========================================
--changeset christian:006
CREATE TABLE IF NOT EXISTS public.notificacion (
    id_notificacion BIGINT NOT NULL,
    fecha_programada TIMESTAMP(6),
    leida BOOLEAN,
    mensaje VARCHAR(255),
    tipo VARCHAR(255),
    id_usuario BIGINT NOT NULL
);

--changeset christian:006.1
ALTER TABLE public.notificacion
    ALTER COLUMN id_notificacion ADD GENERATED BY DEFAULT AS IDENTITY
      (SEQUENCE NAME public.notificacion_id_notificacion_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--changeset christian:006.2
ALTER TABLE public.notificacion
    ADD CONSTRAINT notificacion_pkey PRIMARY KEY (id_notificacion);


-- =========================================
-- 007: Create perfil_usuario table
-- =========================================
--changeset christian:007
CREATE TABLE IF NOT EXISTS public.perfil_usuario (
    id_perfil BIGINT NOT NULL,
    biografia VARCHAR(255),
    fecha_actualizacion TIMESTAMP(6),
    foto_perfil VARCHAR(255),
    intereses VARCHAR(255),
    localizacion VARCHAR(255),
    sitio_web VARCHAR(255),
    id_usuario BIGINT,
    descripcion VARCHAR(255)
);

--changeset christian:007.1
ALTER TABLE public.perfil_usuario
    ALTER COLUMN id_perfil ADD GENERATED BY DEFAULT AS IDENTITY
      (SEQUENCE NAME public.perfil_usuario_id_perfil_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--changeset christian:007.2
ALTER TABLE public.perfil_usuario
    ADD CONSTRAINT perfil_usuario_pkey PRIMARY KEY (id_perfil);

--changeset christian:007.3
ALTER TABLE public.perfil_usuario
    ADD CONSTRAINT UK8g58t76k72vrgdttpoq11987x UNIQUE (id_usuario);


-- =========================================
-- 008: Create trackpoint table
-- =========================================
--changeset christian:008
CREATE TABLE IF NOT EXISTS public.trackpoint (
    id_trackpoint BIGINT NOT NULL,
    altitude_meters REAL,
    distance_meters REAL,
    heart_rate INTEGER,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    "time" TIMESTAMP(6),
    id_lap BIGINT NOT NULL
);

--changeset christian:008.1
ALTER TABLE public.trackpoint
    ALTER COLUMN id_trackpoint ADD GENERATED BY DEFAULT AS IDENTITY
      (SEQUENCE NAME public.trackpoint_id_trackpoint_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--changeset christian:008.2
ALTER TABLE public.trackpoint
    ADD CONSTRAINT trackpoint_pkey PRIMARY KEY (id_trackpoint);


-- =========================================
-- 009: Create trackpoint_extension table
-- =========================================
--changeset christian:009
CREATE TABLE IF NOT EXISTS public.trackpoint_extension (
    id_trackpoint_extension BIGINT NOT NULL,
    run_cadence INTEGER,
    speed REAL,
    id_trackpoint BIGINT NOT NULL
);

--changeset christian:009.1
ALTER TABLE public.trackpoint_extension
    ALTER COLUMN id_trackpoint_extension ADD GENERATED BY DEFAULT AS IDENTITY
      (SEQUENCE NAME public.trackpoint_extension_id_trackpoint_extension_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

--changeset christian:009.2
ALTER TABLE public.trackpoint_extension
    ADD CONSTRAINT trackpoint_extension_pkey PRIMARY KEY (id_trackpoint_extension);

--changeset christian:009.3
ALTER TABLE public.trackpoint_extension
    ADD CONSTRAINT UK266bfwb843u5128cg0t32lyi8 UNIQUE (id_trackpoint);


-- =========================================
-- 010: Add all FK constraints
--      (se asume que las tablas ya existen)
-- =========================================
--changeset christian:010
ALTER TABLE public.entrenamiento
  ADD CONSTRAINT FK5oonb16mtjutbblum8jq56tr8
  FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);

--changeset christian:010.1
ALTER TABLE public.entrenamiento
  ADD CONSTRAINT FK5oonb16mtjutbblum8jq56tr8_actividad
  FOREIGN KEY (id_actividad) REFERENCES public.entrenamiento(id_entrenamiento);

--changeset christian:010.2
ALTER TABLE public.lap
  ADD CONSTRAINT FK8jhhhdtrf559me0r8qhit4kcj
  FOREIGN KEY (id_entrenamiento) REFERENCES public.entrenamiento(id_entrenamiento);

--changeset christian:010.3
ALTER TABLE public.lap_extension
  ADD CONSTRAINT FKmpe7jefp4r68bpn8nr0c9cxkj
  FOREIGN KEY (id_lap) REFERENCES public.lap(id_lap);

--changeset christian:010.4
ALTER TABLE public.notificacion
  ADD CONSTRAINT FKba4ejaf2k5khna07117kbgvpt
  FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);

--changeset christian:010.5
ALTER TABLE public.perfil_usuario
  ADD CONSTRAINT FK98iid80tdwlf5sljhnnogmpmt
  FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);

--changeset christian:010.6
ALTER TABLE public.trackpoint
  ADD CONSTRAINT FK83qd64yaernsllkbaljhob71c
  FOREIGN KEY (id_lap) REFERENCES public.lap(id_lap);

--changeset christian:010.7
ALTER TABLE public.trackpoint_extension
  ADD CONSTRAINT FK7opcw0dsw83heik65abrse8v6
  FOREIGN KEY (id_trackpoint) REFERENCES public.trackpoint(id_trackpoint);
